name: Linting

on: #this workflow runs on pull requests and pushes to main or master
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

#this is a list of all jobs
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM Install
        run: npm ci

      - name: Run esLint
        run: npm run eslint
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM Install
        run: npm ci

      - name: Run styleLint
        run: npm run stylelint
